version: '3.6'

volumes:
  app-db-coin-history2:

services:
  db:
    image: timescale/timescaledb:latest-pg11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: coin-history
      POSTGRES_USER: noah
      POSTGRES_PASSWORD: password
    volumes:
      - app-db-coin-history2:/var/lib/postgresql/data
